#!/usr/bin/env python3
"""Bundle the multi-file Windows GUI launcher into one PowerShell script."""

from __future__ import annotations

import argparse
import base64
import re
import textwrap
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
ENTRY_FILE = REPO_ROOT / "installer_launcher_gui.ps1"
BOOTSTRAP_FILE = REPO_ROOT / "gui" / "bootstrap.ps1"
GUI_DIR = REPO_ROOT / "gui"
XAML_DIR = GUI_DIR / "xaml"


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8-sig")


def parse_module_order(bootstrap_text: str) -> list[str]:
    match = re.search(r"\$moduleNames\s*=\s*@\((.*?)\)", bootstrap_text, re.S)
    if not match:
        raise ValueError("Cannot find $moduleNames in gui/bootstrap.ps1")
    module_names = re.findall(r'"([^"]+\.ps1)"', match.group(1))
    if not module_names:
        raise ValueError("Cannot parse GUI module load order")
    return module_names


def split_entry(entry_text: str) -> tuple[str, str]:
    bootstrap_marker = "$bootstrapPath ="
    dispatch_marker = "try {"
    if bootstrap_marker not in entry_text:
        raise ValueError(f"Cannot find entry bootstrap marker: {bootstrap_marker}")
    if dispatch_marker not in entry_text:
        raise ValueError(f"Cannot find entry dispatch marker: {dispatch_marker}")
    prefix = entry_text.split(bootstrap_marker, 1)[0].rstrip()
    suffix = entry_text[entry_text.index(dispatch_marker) :].lstrip()
    return prefix, suffix


def make_bundled_xaml_block() -> str:
    xaml_files = sorted(XAML_DIR.glob("*.xaml"))
    if not xaml_files:
        raise ValueError("No XAML files found under gui/xaml")

    lines = [
        "#region bundled: gui/xaml resources",
        "$script:BundledXamlResources = @{}",
    ]
    for path in xaml_files:
        # XAML files in this repo are UTF-8 with BOM. Embedding raw bytes keeps
        # the BOM in the decoded string, and Windows PowerShell 5.1 can then
        # fail the [xml] cast with "specified node cannot be inserted" errors.
        xaml_text = read_text(path)
        encoded = base64.b64encode(xaml_text.encode("utf-8")).decode("ascii")
        wrapped = "\n".join(textwrap.wrap(encoded, width=96))
        lines.extend(
            [
                '$script:BundledXamlResources["{0}"] = @"'.format(path.name),
                wrapped,
                '"@',
            ]
        )
    lines.append("#endregion bundled: gui/xaml resources")
    return "\n".join(lines)


def make_module_block(module_name: str) -> str:
    path = GUI_DIR / module_name
    if not path.is_file():
        raise FileNotFoundError(f"GUI module not found: {path}")
    relative = path.relative_to(REPO_ROOT).as_posix()
    body = read_text(path).strip()
    return "\n".join(
        [
            f"#region bundled: {relative}",
            body,
            f"#endregion bundled: {relative}",
        ]
    )


def compile_gui(output_path: Path) -> None:
    entry_text = read_text(ENTRY_FILE)
    bootstrap_text = read_text(BOOTSTRAP_FILE)
    prefix, suffix = split_entry(entry_text)
    module_names = parse_module_order(bootstrap_text)

    parts = [
        "# This file is generated by tools/compile_gui.py. Do not edit this file directly.",
        "# Source files: installer_launcher_gui.ps1, gui/*.ps1, gui/xaml/*.xaml",
        "",
        prefix,
        "",
        "#region bundled: gui/bootstrap.ps1 compatibility",
        "$script:GuiRoot = Join-Path $script:RepoRoot \"gui\"",
        "$script:GuiXamlHome = Join-Path $script:GuiRoot \"xaml\"",
        "#endregion bundled: gui/bootstrap.ps1 compatibility",
        "",
        make_bundled_xaml_block(),
        "",
    ]

    for module_name in module_names:
        parts.append(make_module_block(module_name))
        parts.append("")

    parts.append(suffix.rstrip())
    output = "\n".join(parts).rstrip() + "\n"

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(output, encoding="utf-8-sig", newline="\r\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Bundle the Windows GUI launcher into a single PowerShell file.")
    parser.add_argument(
        "--output",
        default=str(REPO_ROOT / "dist" / "installer_launcher_gui.ps1"),
        help="Output PowerShell file. Defaults to dist/installer_launcher_gui.ps1.",
    )
    args = parser.parse_args()
    compile_gui(Path(args.output).resolve())


if __name__ == "__main__":
    main()
