name: Release

on:
  push:
    branches: [main]
    paths:
      - 'installer_launcher.sh'
      - 'installer_launcher_gui.ps1'
      - 'install.sh'
      - 'install.ps1'
      - 'gui/**'
      - 'tools/compile_gui.py'
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  Release-Task:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Installer Launcher
            gh_tag: launcher
            gt_id: launcher
            files: |
              install.sh
              install.ps1
              installer_launcher.sh
              dist/installer_launcher_gui.ps1
              dist/installer_launcher_gui.bat
              install.bat

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install requests requests-toolbelt psh2bat

      - name: Compile GUI release script
        shell: bash
        run: |
          python "${{ github.workspace }}/tools/compile_gui.py" --output "${{ github.workspace }}/dist/installer_launcher_gui.ps1"

      - name: Convert PowerShell script to Bat script
        shell: bash
        run: |
          python -m psh2bat "${{ github.workspace }}/install.ps1" --output-path "${{ github.workspace }}/install.bat"
          python -m psh2bat "${{ github.workspace }}/dist/installer_launcher_gui.ps1" --output-path "${{ github.workspace }}/dist/installer_launcher_gui.bat"

      - name: Release ${{ matrix.name }} to GitHub
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
          github_release_tag: ${{ matrix.gh_tag }}
          github_files: ${{ matrix.files }}
        run: bash "${{ github.workspace }}/.github/github_release.sh"

      - name: Release ${{ matrix.name }} to Gitee
        shell: bash
        env:
          gitee_owner: licyk
          gitee_repo: sd-webui-all-in-one-launcher
          gitee_token: ${{ secrets.gitee_token }}
          gitee_upload_retry_times: 3
          gitee_release_id: ${{ matrix.gt_id }}
          gitee_files: ${{ matrix.files }}
        run: python "${{ github.workspace }}/.github/gitee_release.py"
